version: '3.3'
services:
  db:
    image: postgres:13-alpine
    env_file: 
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: foodgram_db

  frontend:
    image: akuman/foodgram_frontend
    env_file:
      - ./.env
    volumes:
      - ../frontend/:/app/result_build/
    container_name: foodgram_frontend
    depends_on:
      - backend

  backend:
    image: akuman/foodgram_backend
    env_file: 
      - .env
    restart: always
    volumes:
      - static_vol:/app/static/
      - media_vol:/app/media/
      - data_vol:/app/data/
    depends_on:
      - db
    container_name: foodgram_backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../frontend/build:/usr/share/nginx/html/
      - data_vol:/var/html/data
      - static_vol:/var/html/static
      - media_vol:/var/html/media
    restart: always
    depends_on:
      - backend
      - frontend
    container_name: foodgram_nginx

volumes:
  pg_data:
  media_vol:
  static_vol:
  data_vol:
