version: '3.3'

volumes:
  pg_data:
  media_vol:
  frontend_vol:
  static_vol:
  logs_vol:

services:
  db:
    image: postgres:13-alpine
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    # image: akuman/foodgram_backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - static_vol:/app/static/
      - media_vol:/app/media/
    depends_on:
      - db
  frontend:
    # image: akuman/foodgram_frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - frontend_vol:/app/result_build/
  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - frontend_vol:/usr/share/nginx/html/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/
      - logs_vol:/var/logs/
    depends_on:
      - backend
      - frontend
